---
AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/**/*
    - tmp/**/*
    - '**/*.rake'

Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Exclude:
    - '**/*_spec.rb'

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Exclude:
    - lib/name_tamer/name.rb
    - lib/name_tamer/string.rb

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/LineLength:
  Max: 120
  Enabled: true

Metrics/MethodLength:
  Max: 23
  Enabled: true

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Exclude:
    - lib/name_tamer/constants.rb

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
