sonar.projectKey=dominicsayers_name_tamer
sonar.organization=dominicsayers
sonar.sources=lib
sonar.tests=spec
sonar.ruby.coverage.reportPaths=coverage/coverage.json
sonar.ruby.rubocop.reportPaths=rubocop.json
