# frozen_string_literal: true

# When strings are mistakenly encoded as single-byte character sets, instead
# of UTF-8, there are some distinctive character combinations that we can spot
# and fix
# Useful table here http://www.i18nqa.com/debug/utf8-debug.html
class String # rubocop:disable Metrics/ClassLength
  # Strings that were wrongly encoded with single-byte encodings sometimes have
  # tell-tale substrings that we can put back into the correct UTF-8 character
  def fix_encoding_errors!
    gsub!(BAD_ENCODING_PATTERNS) { |substring| BAD_ENCODING[substring] || substring } || self
  end

  BAD_ENCODING = {
    "\xC3\x8D" => 'Í',
    "\xC3\x8F" => 'Ï',
    "\xC3\x90" => 'Ð',
    "\xC3\x9D" => 'Ý',
    'Â ' => ' ',
    'Â¡' => '¡',
    'Â¢' => '¢',
    'Â£' => '£',
    'Â¤' => '¤',
    'Â¥' => '¥',
    'Â¦' => '¦',
    'Â§' => '§',
    'Â¨' => '¨',
    'Â©' => '©',
    'Âª' => 'ª',
    'Â«' => '«',
    'Â¬' => '¬',
    'Â­' => '­',
    'Â®' => '®',
    'Â¯' => '¯',
    'Â°' => '°',
    'Â±' => '±',
    'Â²' => '²',
    'Â³' => '³',
    'Â´' => '´',
    'Âµ' => 'µ',
    'Â¶' => '¶',
    'Â·' => '·',
    'Â¸' => '¸',
    'Â¹' => '¹',
    'Âº' => 'º',
    'Â»' => '»',
    'Â¼' => '¼',
    'Â½' => '½',
    'Â¾' => '¾',
    'Â¿' => '¿',
    'â‚¬' => '€',
    'â„¢' => '™',
    'â€' => '”', # Note the invisible Ux009D in the key
    'â€ ' => '†',
    'â€¡' => '‡',
    'â€¢' => '•',
    'â€¦' => '…',
    'â€°' => '‰',
    'â€²' => '′', # Manually added. Some seem to use this instead of Ux2019
    'â€¹' => '‹',
    'â€º' => '›',
    'â€œ' => '“',
    'â€š' => '‚',
    'â€ž' => '„',
    'â€˜' => '‘',
    'â€“' => '–',
    'â€”' => '—',
    'â€™' => '’',
    'Ã ' => 'à',
    'Ã¡' => 'á',
    'Ã¢' => 'â',
    'Ã£' => 'ã',
    'Ã¤' => 'ä',
    'Ã¥' => 'å',
    'Ã¦' => 'æ',
    'Ã§' => 'ç',
    'Ã¨' => 'è',
    'Ã©' => 'é',
    'Ãª' => 'ê',
    'Ã«' => 'ë',
    'Ã¬' => 'ì',
    'Ã­' => 'í',
    'Ã®' => 'î',
    'Ã¯' => 'ï',
    'Ã°' => 'ð',
    'Ã±' => 'ñ',
    'Ã²' => 'ò',
    'Ã³' => 'ó',
    'Ã´' => 'ô',
    'Ãµ' => 'õ',
    'Ã¶' => 'ö',
    'Ã·' => '÷',
    'Ã¸' => 'ø',
    'Ã¹' => 'ù',
    'Ãº' => 'ú',
    'Ã»' => 'û',
    'Ã¼' => 'ü',
    'Ã½' => 'ý',
    'Ã¾' => 'þ',
    'Ã¿' => 'ÿ',
    'ÃŸ' => 'ß',
    'ÃŒ' => 'Ì',
    'Ãœ' => 'Ü',
    'ÃŠ' => 'Ê',
    'Ãš' => 'Ú',
    'ÃŽ' => 'Î',
    'Ãž' => 'Þ',
    'Ãƒ' => 'Ã',
    'Ãˆ' => 'È',
    'Ã˜' => 'Ø',
    'Ã–' => 'Ö',
    'Ã—' => '×',
    'Ã‘' => 'Ñ',
    'Ã’' => 'Ò',
    'Ã‚' => 'Â',
    'Ã“' => 'Ó',
    'Ã”' => 'Ô',
    'Ã„' => 'Ä',
    'Ã†' => 'Æ',
    'Ã‡' => 'Ç',
    'Ã•' => 'Õ',
    'Ã…' => 'Å',
    'Ã‰' => 'É',
    'Ã‹' => 'Ë',
    'Ã›' => 'Û',
    'Ã€' => 'À',
    'Ã™' => 'Ù',
    'Ã�' => 'Á',
    'Å ' => 'Š',
    'Å¡' => 'š',
    'Å¸' => 'Ÿ',
    'Å½' => 'Ž',
    'Å¾' => 'ž',
    'Å’' => 'Œ',
    'Å“' => 'œ',
    'Æ’' => 'ƒ',
    'Ëœ' => '˜',
    'Ë†' => 'ˆ',
    "\x00" => '', # Manually added to avoid Bad Argument exception
  }.freeze

  BAD_ENCODING_PATTERNS = /(#{BAD_ENCODING.keys.join('|')})/.freeze
end
